/**
 * CONCEPT: Security Check for File Deletion — Path Validation
 *
 * When an admin deletes a gallery item, the server also removes the file
 * from disk. But we must NEVER delete files outside the uploads directory —
 * an attacker could craft a path like "/etc/passwd" or "/../../../important-file".
 *
 * This function acts as a security gate: only paths starting with the known
 * upload prefix are allowed to be deleted. This is a "whitelist" approach —
 * deny by default, allow only known-safe paths.
 *
 * In production, you'd also check for path traversal (`..`) and normalize
 * the path before comparison. Here the simple prefix check suffices because
 * upload paths are generated by the server, not user input.
 */

/** Paths that may be deleted when removing an album or media (admin uploads). */
export function isGalleryManagedUpload(src: string): boolean {
  // Only allow deletion of files we created in the managed upload directory
  return src.startsWith("/uploads/gallery/");
}
