/**
 * CONCEPT: HTML Parsing with Regex + Backward Compatibility
 *
 * This module extracts media (images, videos, YouTube embeds) from legacy HTML
 * that was stored before structured fields were introduced. It uses regex
 * to parse HTML — generally discouraged for complex HTML, but acceptable here
 * because we control the HTML format (it was generated by our own compose function).
 *
 * Key regex techniques:
 * - `exec()` in a while loop — iterates over ALL matches in a string
 * - `RegExpExecArray` type — the return type of `exec()`, with index and groups
 * - Non-greedy `[^>]+` — match tag attributes without crossing tag boundaries
 * - `Set` for deduplication — prevents the same image from appearing twice
 */

import { inferVideoMime } from "@/lib/news-compose-body";

/** Extracts media from old article HTML (before structured fields) for display below the text. */
export function parseLegacyMediaFromBodyHtml(bodyHtml: string): {
  images: string[];
  youtubeEmbeds: string[];
  videos: { src: string; mime: string }[];
} {
  const images: string[] = [];
  const seenImg = new Set<string>(); // Deduplication — same src won't appear twice
  // CONCEPT: `exec()` loop pattern — each call advances the regex's lastIndex,
  // returning the next match until no more are found (returns null).
  const imgRe = /<img[^>]+src="([^"]+)"/gi;
  let m: RegExpExecArray | null;
  while ((m = imgRe.exec(bodyHtml)) !== null) {
    const src = m[1]; // Capture group 1 = the src attribute value
    if (src?.startsWith("/uploads/") && !seenImg.has(src)) {
      seenImg.add(src);
      images.push(src);
    }
  }

  const youtubeEmbeds: string[] = [];
  const iframeRe = /<iframe[^>]+src="([^"]+)"/gi;
  while ((m = iframeRe.exec(bodyHtml)) !== null) {
    const src = m[1];
    if (src?.includes("youtube")) youtubeEmbeds.push(src);
  }

  const videos: { src: string; mime: string }[] = [];
  const vidBlockRe = /<video[\s\S]*?<\/video>/gi;
  let block: RegExpExecArray | null;
  while ((block = vidBlockRe.exec(bodyHtml)) !== null) {
    const blockHtml = block[0];
    const srcM = /<source[^>]+src="([^"]+)"(?:[^>]+type="([^"]+)")?/i.exec(blockHtml);
    if (srcM?.[1]?.startsWith("/uploads/")) {
      const mime = srcM[2] || inferVideoMime(srcM[1]) || "video/mp4";
      videos.push({ src: srcM[1], mime });
    }
  }

  return { images, youtubeEmbeds, videos };
}

/** Only the `<div class="news-body">…</div>` fragment for displaying text in the article. */
export function extractNewsBodyHtmlFragment(fullHtml: string): string {
  const m = fullHtml.match(/<div class="news-body">[\s\S]*?<\/div>/);
  return m ? m[0] : fullHtml;
}
